using Pkg
Pkg.activate(".")
Pkg.add([
  PackageSpec(name="ITensors"),
  PackageSpec(name="ITensorMPS"),
  PackageSpec(name="CUDA"),
  PackageSpec(name="CSV"),
  PackageSpec(name="DataFrames"),
])
Pkg.status()